[project]
name = "tb2j_workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10",
    "mp-api>=0.46.4",
    "pymatgen>=2026.5.4",
    "tb2j>=0.9.20",
]

[project.scripts]
gen-scf = "tb2j_workflow.scf.generate_scf_input:main"
gen-w90 = "tb2j_workflow.wannier90.generate_wannier90_input:main"
gen-tb2j = "tb2j_workflow.tb2j.generate_tb2j_input:main"
gen-vampire = "tb2j_workflow.vampire.generate_vampire_input:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/tb2j_workflow"]
